### ISSUE TITLE
Promise & Function return support

### ISSUE THREAD

**Issue by SergeShkurko** [nicolasgere/graphql-ts#10]
graphql-ts not support Function & Promise how objectType method return type
![2](https://user-images.githubusercontent.com/18213789/29821883-ef4bacec-8ce2-11e7-87c7-067482eafb63.PNG)
![default](https://user-images.githubusercontent.com/18213789/29822355-9b439180-8ce4-11e7-8d29-4a5a75033f36.PNG)

![default](https://user-images.githubusercontent.com/18213789/29821887-f2f33b4e-8ce2-11e7-8de7-6c89e0482179.PNG)
![2](https://user-images.githubusercontent.com/18213789/29822358-9ea92272-8ce4-11e7-84ea-12375e673d94.PNG)

But the standard graphql supports it normally
![default](https://user-images.githubusercontent.com/18213789/29821992-5a612bf6-8ce3-11e7-8a31-96b696640d3e.PNG)
Please fix it bug, thanks

**Comment by nicolasgere** [comment]
@SergeShkurko i will work on that when i have time, in 2 week max, thanks for the feedback

**Comment by pie6k** [comment]
Any update?

**Comment by nicolasgere** [comment]
i will try to do something this weekend. Sorry

**Comment by nicolasgere** [comment]
@pie6k , @SergeShkurko due to typescript metadata support for complexe type, you have to specify the return type with `@returnType(date)` . You can see a discution about this [here](https://github.com/Microsoft/TypeScript/issues/14971)

and for the function return type i see  nothing about this in the graphql specification, can i have a link?

**Comment by poliron0** [comment]
@nicolasgere It's mentioned here: https://github.com/graphql/graphql-js
under Getting Started/Using GraphQL.js subsection. 

> The resolve function can return a value, a promise, or an array of promises. A more complex example is included in the top level tests directory.

![image](https://user-images.githubusercontent.com/6294372/31502873-de1090a8-af76-11e7-882a-dbb06053a79f.png)

**Comment by nicolasgere** [comment]
@poliron0 , GraphQl-ts support both, just do not forget to specify `@returnType(T)`
