### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by 4F2E4A2E** [nicolasgere/graphql-ts#12]
IMHO a lib like this has a very high potential in becoming one of the  most important libs around graphql.
Define your typings in typescript, once, that's amazing.

But, it seams broken and not maintained , whats the deal?

**Comment by nicolasgere** [comment]
Hello, i will start to maintain it if people needed. It was a side project, do you have an error ?

**Comment by 4F2E4A2E** [comment]
thanks @nicolasgere 
I really believe that a tool like this is paramount for the enterprise sector &/ big &/ complex app projects using typescript. Right now i am heading over to the type-graphql project. It seams to be the best shot for now, but I am also interesting in your feedback.

What i am trying to cover is a complete types definitions in typescript. This example is not working for me - could well be of wrong usage - , because User class ist extending the UserBase class:

```typescript
import { field, graphqlTs, objectType } from 'graphql-ts';

@objectType
export abstract class UserBase {
  @field
  version: number;
}

@objectType
export abstract class Status {
  @field
  alive: boolean;
}

@objectType
export abstract class User extends UserBase {
  @field
  name: string;
  @field
  status: Status;
}

@objectType
class Root {
  @field
  user(): User {
    return {
      version: 42,
      name:    'Foo',
      status: {alive: true}
    } as User;
  }
}

graphqlTs.init(new Root());

const queryString = '{ user{ name status{alive} version }}';
graphqlTs.query(queryString)
  .then(result => {
    console.log(result);
  });

```


```typescript
$ ts-node src/test.ts
{ errors:
   [ { GraphQLError: Cannot query field "version" on type "User".
    at Object.Field (.\node_modules\graphql-ts\node_modules\graphql\validation\rules\FieldsOnCorrectType.js:66:31)
    at Object.enter (.\node_modules\graphql-ts\node_modules\graphql\language\visitor.js:297:29)
    at Object.enter (.\node_modules\graphql-ts\node_modules\graphql\language\visitor.js:339:25)
    at visit (.\node_modules\graphql-ts\node_modules\graphql\language\visitor.js:229:26)
    at visitUsingRules (.\node_modules\graphql-ts\node_modules\graphql\validation\validate.js:76:22)
    at validate (.\node_modules\graphql-ts\node_modules\graphql\validation\validate.js:61:10)
    at .\node_modules\graphql-ts\node_modules\graphql\graphql.js:72:51
    at new Promise (<anonymous>)
    at graphqlImpl (.\node_modules\graphql-ts\node_modules\graphql\graphql.js:62:10)
    at Object.graphql (.\node_modules\graphql-ts\node_modules\graphql\graphql.js:50:148)
       message: 'Cannot query field "version" on type "User".',
       locations: [Array],
       path: undefined } ] }
```

**Comment by nicolasgere** [comment]
I dont think extends its supported, it could be a cool feature.
I will check that this week, i let you know

**Comment by pie6k** [comment]
Since this repo does not really feel active, I'd like to tell about library I've created allowing creating schema with decorators -

https://github.com/prismake/typegql

**Comment by MichalLytek** [comment]
As we compete with pie6k about who will have a more famous GraphQL framework for TypeScript, I will advertise here too with my [TypeGraphQL](https://19majkel94.github.io/type-graphql) 😄 
It has more advanced features like support for interfaces and inheritance, subscriptions, validation and dependency injection 😉

**Comment by 4F2E4A2E** [comment]
I am closing this issue, since we decided to go for [typegql](https://github.com/prismake/typegql) and [swagger-to-graphql](https://github.com/yarax/swagger-to-graphql). type-graphql is a opionated lib, for us it was not possible using it without implementing extra logic into our entities.

**Comment by pie6k** [comment]
I think your `typegql` link leads to `type-graphql`

**Comment by 19majkel94** [comment]
> type-graphql is a opionated lib

Could you describe what exactly is opinionated? 😕 I think only integration with `class-validator`, which can be disabled if you want joi or sth else.

**Comment by nicolasgere** [comment]
@4F2E4A2E you can do a pr in this repo, on the readme to add a link to your repo if you want

**Comment by pie6k** [comment]
@nicolasgere I've created #14

**Comment by MichalLytek** [comment]
Alternative libraries can be found in [awesome-graphql](https://github.com/chentsulin/awesome-graphql) list:
https://github.com/chentsulin/awesome-graphql#lib-ts
