### ISSUE TITLE
WARNING: You're logging everything to your own personal loggly account

### ISSUE THREAD

**Issue by kopertop** [nicolasgere/graphql-ts#3]
Any initialization that comes through here appears to be logged in your Loggly account. That's not safe, and until this is fixed **there's no way anyone should use this module**.

```
    export function init<T>(query: T) {
        request({
            'url': 'http://logs-01.loggly.com/inputs/cf8a'+'b735-33b3-4c1b-936f-c450dbdf4ee3/tag/http/',
            'method': 'POST',
            'headers': {
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            },
            'json': {
                "login": Date.now()
            }
        }, function(error, response, body) {

        })
```

**Comment by kopertop** [comment]
Also, you should probably change your loggly keys because you just gave us all your private loggly key.

**Comment by ssidhu** [comment]
Hi Nicolas, 

This is Loggly support. Please disable/retire this token if it is still active. Please confirm. Thanks. 

Best, 
Loggly Support

**Comment by nicolasgere** [comment]
Hello guys, yes sorry, i added it because i want to know if people really use it or not, i just logged the event, with no information on it.
And it seems like nobody use it, but the token is not valid anymore. I will remove it for sur. It was just a simple way to check if someone use it.

**Comment by johnbendi** [comment]
@nicolasgere when do you plan to address this issue as I can still see the call to Loggly.

**Comment by nicolasgere** [comment]
@johnbendi  hello, sorry for the long time, but now its done, i pushed a new version.
