### ISSUE TITLE
Schema must be an instance of GraphQLSchema

### ISSUE THREAD

**Issue by mydnicq** [nicolasgere/graphql-ts#4]
I've started using this excellent module. It really simplifies GraphQL schema generation.

However, I've encountered a small problem with generated schema. In Graphiql editor I got an error 'Schema must be an instance of GraphQLSchema'. After debuging I found that problem lies in your module package.json, where graphql module is defined as devDependency.  My project also has graphql module as devDependency and creators of graphql stated that there should be only one graphql module per project. 

So I recommend that you change graphql module devDependency to peerDependency.

**Comment by nicolasgere** [comment]
Thank you for the feedback,
I will do it, or maybe you can do a small pr for that :+1:

**Comment by mydnicq** [comment]
PR is done so I'm closing this.
