### ISSUE TITLE
Access context in mutations

### ISSUE THREAD

**Issue by BrandonRbg** [nicolasgere/graphql-ts#7]
Is it possible to have access to context in a mutation? Seems like it's not injected in the variable _context.

**Comment by BrandonRbg** [comment]
Made a PR fixing the issue. https://github.com/nicolasgere/graphql-ts/pull/8

**Comment by nicolasgere** [comment]
Thank you, is merge, i will fixe the dependency for fix the CI. Thanks a lot

**Comment by BrandonRbg** [comment]
Can you update the package on NPM too? Thanks a lot.

**Comment by nicolasgere** [comment]
yes i will do it before tomorow

**Comment by nicolasgere** [comment]
tell me if everything is ok @SirKhepre
