### ISSUE TITLE
Old project similar to this one

### ISSUE THREAD

**Issue by aliksend** [nicolasgere/graphql-ts#9]
Thank you for your project.
Have you seen [graphql-decorator](https://github.com/Quramy/graphql-decorator)? I think you can take something from this

**Comment by aliksend** [comment]
Some small fixes.
Are you really need `@types/request` as depency?
In second example in `README.md` (just above word "Decorator"):
- `import {graphql} from 'graphql'` probably unused
- decorators isn't imported
- `root` class doesn't have decorator

Feature request: custom param name, `description` param (may be as decorator argument)

**Comment by nicolasgere** [comment]
Hello @aliksend thanks for your feedback,
 yes i found this repo later, but at the end we do the same things.
If i remember well description is present, you can use it.
And what do you mean by custom param name?

**Comment by aliksend** [comment]
I think that you can find some solutions that can be useful for your project.
Sorry about description, my mistake.
About custom names. If I want have `user_login` field in my class, but want that it will be `login` in schema, how I can do it?

**Comment by aliksend** [comment]
Also I have found other [similar project](https://github.com/indigotech/graphql-schema-decorator)

**Comment by nicolasgere** [comment]
thank you for the link and the feedback, i will check that.
Currently it's not possible to do that. If you want i can check that, or if you want to add it, you re welcome.
I fixed the package json and remove useless dependency.
